version: 2
jobs:
  build-test-backend:
    working_directory: ~/SEPT-M2-CI/BackEnd/majorProject
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root1
          POSTGRES_DB: db
    steps:
      - checkout:
          path: ~/SEPT-M2-CI
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/majorProject-0.0.1-SNAPSHOT.jar

  build-test-frontend:
    working_directory: ~/SEPT-M2-CI/FrontEnd
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout:
          path: ~/SEPT-M2-CI
      - restore_cache:
            key: dependencies-frontend-{{ checksum "package.json" }}

      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: dependencies-frontend-{{ checksum "package.json" }}
      - run: npm test

workflows:
  version: 2
  build_backend_and_frontend:
    jobs:
      - build-test-backend
      - build-test-frontend
